name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images for the benchmarks
      run: ./build.sh [nopqrstuvwxyz]*_bench
    - name: Run the benchmarks
      run: ./bench.sh [nopqrstuvwxyz]*_bench
      env:
        GRPC_BENCHMARK_DURATION: "30s"
